[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fonttools = "^4.51.0"
Brotli = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
